name: Check

on:
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix develop .#CI-check --impure --command make --keep-going check
