name: Check

on:
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache
          key: ${{ hashFiles('deno.lock') }}

      - name: Verify formatting
        run: deno fmt --check core nusa

      - name: Run linter
        run: deno lint core nusa

      - name: Run type checker
        run: deno check `find core nusa -type f -and \( -name "*.ts" -o -name "*.mts" \)`

      - name: Setup puppeteer
        run: PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer/install.ts

      - name: Run tests
        run: deno task ci:test
