name: Publich to npm

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v2
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/deno
          key: ${{ hashFiles('deno.lock') }}
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/soupault
          key: ${{ hashFiles('soupault.toml') }}

      - run: nix develop .#js-bundler --command "make result/packages"

      - name: Publish
        run: | # TODO: generate package.json{workspaces} to simplify npm publish
          cd result/packages
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
