name: Publich to npm

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: experimental-features = nix-command flakes
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/deno
          key: ${{ hashFiles('deno.lock') }}

      - run: nix develop .#js-bundler --impure --command "make result/packages"

      - name: Publish
        run: | # TODO: generate package.json{workspaces} to simplify npm publish
          cd result/packages
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
