name: Deploy Web Site

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ hashFiles('deno.lock') }}

      - name: Build
        # run: deno task build --quiet # BUG(lume): --quiet disable checkUpgrade() because `sha` might be undefined https://github.com/lumeland/lume/blob/master/core/utils.ts#L136
        run: | # BUG(lume): somehow esbuild service stop and cause to return execution with exit code 1, works fine (exit code 0) when running on local machine
          deno task build || true
          tree _site/

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nusa
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
