name: Deploy Web Site

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/deno
          key: ${{ hashFiles('deno.lock') }}
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/soupault
          key: ${{ hashFiles('soupault.toml') }}

      - run: nix develop .#CI-site --impure --command make

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nusa
          directory: result/site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
